version: '2'

services:
  maven-nexus:
     image: sonatype/nexus3:3.14.0
     restart: always
     container_name: maven-nexus
     ports:
       - "8081:8081"
     volumes:
       - /tmp/nexus-data:/opt/sonatype/sonatype-work/nexus3
     networks:
       - nexus-docker


networks:
  nexus-docker:
    driver: bridge
